name: Tests

#
# Run unit tests and fail if coverage is below threshold
#

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]
    branches:
      - '*'
env:
  CODE_DIRS: kennyupullgosdk

jobs:
  build:
    name: >-
     ubuntu-latest
      /
      1.17
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests and check coverage
        run: |
          go test -v -coverprofile=coverage.out ./...
          COVERAGE=$(go tool cover -func=coverage.out | sed -n '/total/p' | awk '{print substr($NF, 1, length($NF)-1)}')
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
              echo "Coverage is below 90%: $COVERAGE%"
              exit 1
          fi
